### ISSUE TITLE
The login field, placeholder, error texts are misalligned, malformed.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#131]
The login screen is currently malformed and does not appear as designed:

http://prntscr.com/bm19om
http://prntscr.com/bm1acb

The various texts are outside of the field.

**Comment by daonb** [comment]
It looks good on the development env (using `gulp serve`). seems like there's a css rule that didn't make it to dist :
```css 
    .modal .modal-dialog .auth-modal .auth-form .bhf__field input[type=text], .modal .modal-dialog .auth-modal .auth-form .bhf__field input[type=password], .modal .modal-dialog .auth-modal .auth-form .bhf__field input[type=email], .modal .modal-dialog .auth-modal .auth-form .bhf__field textarea {
      width: 100%;
      border: 2px solid #d4d6d5;
      border-radius: 6px;
      margin-bottom: 6px;
      padding: 34px 10px 0;
      font-size: 25px; }
```
(code from bhsclient.css lines 241-247)
